import React from 'react'
import { Button } from '@material-ui/core'

const BUTTON_X100_MUI = () => {
    return (
        <React.Fragment>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
        </React.Fragment>
    )
}

export default BUTTON_X100_MUI