import React from 'react'
import { Button } from '@instructure/ui'

const BUTTON_X100_IUI = () => {
    return (
        <React.Fragment>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
            <Button>asd</Button>
        </React.Fragment>
    )
}

export default BUTTON_X100_IUI