import { Flex } from '@instructure/ui'

const FLEX_X100_IUI = () => {

  return (
    <Flex>
      <Flex.Item>Item 0</Flex.Item>
      <Flex.Item>Item 1</Flex.Item>
      <Flex.Item>Item 2</Flex.Item>
      <Flex.Item>Item 3</Flex.Item>
      <Flex.Item>Item 4</Flex.Item>
      <Flex.Item>Item 5</Flex.Item>
      <Flex.Item>Item 6</Flex.Item>
      <Flex.Item>Item 7</Flex.Item>
      <Flex.Item>Item 8</Flex.Item>
      <Flex.Item>Item 9</Flex.Item>
      <Flex.Item>Item 10</Flex.Item>
      <Flex.Item>Item 11</Flex.Item>
      <Flex.Item>Item 12</Flex.Item>
      <Flex.Item>Item 13</Flex.Item>
      <Flex.Item>Item 14</Flex.Item>
      <Flex.Item>Item 15</Flex.Item>
      <Flex.Item>Item 16</Flex.Item>
      <Flex.Item>Item 17</Flex.Item>
      <Flex.Item>Item 18</Flex.Item>
      <Flex.Item>Item 19</Flex.Item>
      <Flex.Item>Item 20</Flex.Item>
      <Flex.Item>Item 21</Flex.Item>
      <Flex.Item>Item 22</Flex.Item>
      <Flex.Item>Item 23</Flex.Item>
      <Flex.Item>Item 24</Flex.Item>
      <Flex.Item>Item 25</Flex.Item>
      <Flex.Item>Item 26</Flex.Item>
      <Flex.Item>Item 27</Flex.Item>
      <Flex.Item>Item 28</Flex.Item>
      <Flex.Item>Item 29</Flex.Item>
      <Flex.Item>Item 30</Flex.Item>
      <Flex.Item>Item 31</Flex.Item>
      <Flex.Item>Item 32</Flex.Item>
      <Flex.Item>Item 33</Flex.Item>
      <Flex.Item>Item 34</Flex.Item>
      <Flex.Item>Item 35</Flex.Item>
      <Flex.Item>Item 36</Flex.Item>
      <Flex.Item>Item 37</Flex.Item>
      <Flex.Item>Item 38</Flex.Item>
      <Flex.Item>Item 39</Flex.Item>
      <Flex.Item>Item 40</Flex.Item>
      <Flex.Item>Item 41</Flex.Item>
      <Flex.Item>Item 42</Flex.Item>
      <Flex.Item>Item 43</Flex.Item>
      <Flex.Item>Item 44</Flex.Item>
      <Flex.Item>Item 45</Flex.Item>
      <Flex.Item>Item 46</Flex.Item>
      <Flex.Item>Item 47</Flex.Item>
      <Flex.Item>Item 48</Flex.Item>
      <Flex.Item>Item 49</Flex.Item>
      <Flex.Item>Item 50</Flex.Item>
      <Flex.Item>Item 51</Flex.Item>
      <Flex.Item>Item 52</Flex.Item>
      <Flex.Item>Item 53</Flex.Item>
      <Flex.Item>Item 54</Flex.Item>
      <Flex.Item>Item 55</Flex.Item>
      <Flex.Item>Item 56</Flex.Item>
      <Flex.Item>Item 57</Flex.Item>
      <Flex.Item>Item 58</Flex.Item>
      <Flex.Item>Item 59</Flex.Item>
      <Flex.Item>Item 60</Flex.Item>
      <Flex.Item>Item 61</Flex.Item>
      <Flex.Item>Item 62</Flex.Item>
      <Flex.Item>Item 63</Flex.Item>
      <Flex.Item>Item 64</Flex.Item>
      <Flex.Item>Item 65</Flex.Item>
      <Flex.Item>Item 66</Flex.Item>
      <Flex.Item>Item 67</Flex.Item>
      <Flex.Item>Item 68</Flex.Item>
      <Flex.Item>Item 69</Flex.Item>
      <Flex.Item>Item 70</Flex.Item>
      <Flex.Item>Item 71</Flex.Item>
      <Flex.Item>Item 72</Flex.Item>
      <Flex.Item>Item 73</Flex.Item>
      <Flex.Item>Item 74</Flex.Item>
      <Flex.Item>Item 75</Flex.Item>
      <Flex.Item>Item 76</Flex.Item>
      <Flex.Item>Item 77</Flex.Item>
      <Flex.Item>Item 78</Flex.Item>
      <Flex.Item>Item 79</Flex.Item>
      <Flex.Item>Item 80</Flex.Item>
      <Flex.Item>Item 81</Flex.Item>
      <Flex.Item>Item 82</Flex.Item>
      <Flex.Item>Item 83</Flex.Item>
      <Flex.Item>Item 84</Flex.Item>
      <Flex.Item>Item 85</Flex.Item>
      <Flex.Item>Item 86</Flex.Item>
      <Flex.Item>Item 87</Flex.Item>
      <Flex.Item>Item 88</Flex.Item>
      <Flex.Item>Item 89</Flex.Item>
      <Flex.Item>Item 90</Flex.Item>
      <Flex.Item>Item 91</Flex.Item>
      <Flex.Item>Item 92</Flex.Item>
      <Flex.Item>Item 93</Flex.Item>
      <Flex.Item>Item 94</Flex.Item>
      <Flex.Item>Item 95</Flex.Item>
      <Flex.Item>Item 96</Flex.Item>
      <Flex.Item>Item 97</Flex.Item>
      <Flex.Item>Item 98</Flex.Item>
      <Flex.Item>Item 99</Flex.Item>
    </Flex>
  )
}

export default FLEX_X100_IUI