import React from 'react'
import { IconAddLine } from '@instructure/ui-icons'

const ICON_X100_IUI = () => {
    return (
        <React.Fragment>
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
            <IconAddLine />
        </React.Fragment>
    )
}

export default ICON_X100_IUI