import React from 'react'
import AddIcon from '@material-ui/icons/Add'

const ICON_X100_MUI = () => {
    return (
        <React.Fragment>
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
            <AddIcon />
        </React.Fragment>
    )
}

export default ICON_X100_MUI