import { Link } from '@instructure/ui'
import React from 'react'

const LINK_X100_IUI = () => {
  return (
    <React.Fragment>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
      <Link href="http://instructure.design">Link</Link>
    </React.Fragment>
  )
}

export default LINK_X100_IUI