import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';

const SIMPLESELECT_X100_MUI = () => {
    return (
        <Select>
            <MenuItem value='a0'>a0</MenuItem>
            <MenuItem value='a1'>a1</MenuItem>
            <MenuItem value='a2'>a2</MenuItem>
            <MenuItem value='a3'>a3</MenuItem>
            <MenuItem value='a4'>a4</MenuItem>
            <MenuItem value='a5'>a5</MenuItem>
            <MenuItem value='a6'>a6</MenuItem>
            <MenuItem value='a7'>a7</MenuItem>
            <MenuItem value='a8'>a8</MenuItem>
            <MenuItem value='a9'>a9</MenuItem>
            <MenuItem value='a10'>a10</MenuItem>
            <MenuItem value='a11'>a11</MenuItem>
            <MenuItem value='a12'>a12</MenuItem>
            <MenuItem value='a13'>a13</MenuItem>
            <MenuItem value='a14'>a14</MenuItem>
            <MenuItem value='a15'>a15</MenuItem>
            <MenuItem value='a16'>a16</MenuItem>
            <MenuItem value='a17'>a17</MenuItem>
            <MenuItem value='a18'>a18</MenuItem>
            <MenuItem value='a19'>a19</MenuItem>
            <MenuItem value='a20'>a20</MenuItem>
            <MenuItem value='a21'>a21</MenuItem>
            <MenuItem value='a22'>a22</MenuItem>
            <MenuItem value='a23'>a23</MenuItem>
            <MenuItem value='a24'>a24</MenuItem>
            <MenuItem value='a25'>a25</MenuItem>
            <MenuItem value='a26'>a26</MenuItem>
            <MenuItem value='a27'>a27</MenuItem>
            <MenuItem value='a28'>a28</MenuItem>
            <MenuItem value='a29'>a29</MenuItem>
            <MenuItem value='a30'>a30</MenuItem>
            <MenuItem value='a31'>a31</MenuItem>
            <MenuItem value='a32'>a32</MenuItem>
            <MenuItem value='a33'>a33</MenuItem>
            <MenuItem value='a34'>a34</MenuItem>
            <MenuItem value='a35'>a35</MenuItem>
            <MenuItem value='a36'>a36</MenuItem>
            <MenuItem value='a37'>a37</MenuItem>
            <MenuItem value='a38'>a38</MenuItem>
            <MenuItem value='a39'>a39</MenuItem>
            <MenuItem value='a40'>a40</MenuItem>
            <MenuItem value='a41'>a41</MenuItem>
            <MenuItem value='a42'>a42</MenuItem>
            <MenuItem value='a43'>a43</MenuItem>
            <MenuItem value='a44'>a44</MenuItem>
            <MenuItem value='a45'>a45</MenuItem>
            <MenuItem value='a46'>a46</MenuItem>
            <MenuItem value='a47'>a47</MenuItem>
            <MenuItem value='a48'>a48</MenuItem>
            <MenuItem value='a49'>a49</MenuItem>
            <MenuItem value='a50'>a50</MenuItem>
            <MenuItem value='a51'>a51</MenuItem>
            <MenuItem value='a52'>a52</MenuItem>
            <MenuItem value='a53'>a53</MenuItem>
            <MenuItem value='a54'>a54</MenuItem>
            <MenuItem value='a55'>a55</MenuItem>
            <MenuItem value='a56'>a56</MenuItem>
            <MenuItem value='a57'>a57</MenuItem>
            <MenuItem value='a58'>a58</MenuItem>
            <MenuItem value='a59'>a59</MenuItem>
            <MenuItem value='a60'>a60</MenuItem>
            <MenuItem value='a61'>a61</MenuItem>
            <MenuItem value='a62'>a62</MenuItem>
            <MenuItem value='a63'>a63</MenuItem>
            <MenuItem value='a64'>a64</MenuItem>
            <MenuItem value='a65'>a65</MenuItem>
            <MenuItem value='a66'>a66</MenuItem>
            <MenuItem value='a67'>a67</MenuItem>
            <MenuItem value='a68'>a68</MenuItem>
            <MenuItem value='a69'>a69</MenuItem>
            <MenuItem value='a70'>a70</MenuItem>
            <MenuItem value='a71'>a71</MenuItem>
            <MenuItem value='a72'>a72</MenuItem>
            <MenuItem value='a73'>a73</MenuItem>
            <MenuItem value='a74'>a74</MenuItem>
            <MenuItem value='a75'>a75</MenuItem>
            <MenuItem value='a76'>a76</MenuItem>
            <MenuItem value='a77'>a77</MenuItem>
            <MenuItem value='a78'>a78</MenuItem>
            <MenuItem value='a79'>a79</MenuItem>
            <MenuItem value='a80'>a80</MenuItem>
            <MenuItem value='a81'>a81</MenuItem>
            <MenuItem value='a82'>a82</MenuItem>
            <MenuItem value='a83'>a83</MenuItem>
            <MenuItem value='a84'>a84</MenuItem>
            <MenuItem value='a85'>a85</MenuItem>
            <MenuItem value='a86'>a86</MenuItem>
            <MenuItem value='a87'>a87</MenuItem>
            <MenuItem value='a88'>a88</MenuItem>
            <MenuItem value='a89'>a89</MenuItem>
            <MenuItem value='a90'>a90</MenuItem>
            <MenuItem value='a91'>a91</MenuItem>
            <MenuItem value='a92'>a92</MenuItem>
            <MenuItem value='a93'>a93</MenuItem>
            <MenuItem value='a94'>a94</MenuItem>
            <MenuItem value='a95'>a95</MenuItem>
            <MenuItem value='a96'>a96</MenuItem>
            <MenuItem value='a97'>a97</MenuItem>
            <MenuItem value='a98'>a98</MenuItem>
            <MenuItem value='a99'>a99</MenuItem>
        </Select>
    )
}

export default SIMPLESELECT_X100_MUI