import { SimpleSelect } from '@instructure/ui-simple-select';

const SIMPLESELECT_X100_IUI = () => {
    return (
        <SimpleSelect>
            <SimpleSelect.Option id="a0" value="a0">a0</SimpleSelect.Option>
            <SimpleSelect.Option id="a1" value="a1">a1</SimpleSelect.Option>
            <SimpleSelect.Option id="a2" value="a2">a2</SimpleSelect.Option>
            <SimpleSelect.Option id="a3" value="a3">a3</SimpleSelect.Option>
            <SimpleSelect.Option id="a4" value="a4">a4</SimpleSelect.Option>
            <SimpleSelect.Option id="a5" value="a5">a5</SimpleSelect.Option>
            <SimpleSelect.Option id="a6" value="a6">a6</SimpleSelect.Option>
            <SimpleSelect.Option id="a7" value="a7">a7</SimpleSelect.Option>
            <SimpleSelect.Option id="a8" value="a8">a8</SimpleSelect.Option>
            <SimpleSelect.Option id="a9" value="a9">a9</SimpleSelect.Option>
            <SimpleSelect.Option id="a10" value="a10">a10</SimpleSelect.Option>
            <SimpleSelect.Option id="a11" value="a11">a11</SimpleSelect.Option>
            <SimpleSelect.Option id="a12" value="a12">a12</SimpleSelect.Option>
            <SimpleSelect.Option id="a13" value="a13">a13</SimpleSelect.Option>
            <SimpleSelect.Option id="a14" value="a14">a14</SimpleSelect.Option>
            <SimpleSelect.Option id="a15" value="a15">a15</SimpleSelect.Option>
            <SimpleSelect.Option id="a16" value="a16">a16</SimpleSelect.Option>
            <SimpleSelect.Option id="a17" value="a17">a17</SimpleSelect.Option>
            <SimpleSelect.Option id="a18" value="a18">a18</SimpleSelect.Option>
            <SimpleSelect.Option id="a19" value="a19">a19</SimpleSelect.Option>
            <SimpleSelect.Option id="a20" value="a20">a20</SimpleSelect.Option>
            <SimpleSelect.Option id="a21" value="a21">a21</SimpleSelect.Option>
            <SimpleSelect.Option id="a22" value="a22">a22</SimpleSelect.Option>
            <SimpleSelect.Option id="a23" value="a23">a23</SimpleSelect.Option>
            <SimpleSelect.Option id="a24" value="a24">a24</SimpleSelect.Option>
            <SimpleSelect.Option id="a25" value="a25">a25</SimpleSelect.Option>
            <SimpleSelect.Option id="a26" value="a26">a26</SimpleSelect.Option>
            <SimpleSelect.Option id="a27" value="a27">a27</SimpleSelect.Option>
            <SimpleSelect.Option id="a28" value="a28">a28</SimpleSelect.Option>
            <SimpleSelect.Option id="a29" value="a29">a29</SimpleSelect.Option>
            <SimpleSelect.Option id="a30" value="a30">a30</SimpleSelect.Option>
            <SimpleSelect.Option id="a31" value="a31">a31</SimpleSelect.Option>
            <SimpleSelect.Option id="a32" value="a32">a32</SimpleSelect.Option>
            <SimpleSelect.Option id="a33" value="a33">a33</SimpleSelect.Option>
            <SimpleSelect.Option id="a34" value="a34">a34</SimpleSelect.Option>
            <SimpleSelect.Option id="a35" value="a35">a35</SimpleSelect.Option>
            <SimpleSelect.Option id="a36" value="a36">a36</SimpleSelect.Option>
            <SimpleSelect.Option id="a37" value="a37">a37</SimpleSelect.Option>
            <SimpleSelect.Option id="a38" value="a38">a38</SimpleSelect.Option>
            <SimpleSelect.Option id="a39" value="a39">a39</SimpleSelect.Option>
            <SimpleSelect.Option id="a40" value="a40">a40</SimpleSelect.Option>
            <SimpleSelect.Option id="a41" value="a41">a41</SimpleSelect.Option>
            <SimpleSelect.Option id="a42" value="a42">a42</SimpleSelect.Option>
            <SimpleSelect.Option id="a43" value="a43">a43</SimpleSelect.Option>
            <SimpleSelect.Option id="a44" value="a44">a44</SimpleSelect.Option>
            <SimpleSelect.Option id="a45" value="a45">a45</SimpleSelect.Option>
            <SimpleSelect.Option id="a46" value="a46">a46</SimpleSelect.Option>
            <SimpleSelect.Option id="a47" value="a47">a47</SimpleSelect.Option>
            <SimpleSelect.Option id="a48" value="a48">a48</SimpleSelect.Option>
            <SimpleSelect.Option id="a49" value="a49">a49</SimpleSelect.Option>
            <SimpleSelect.Option id="a50" value="a50">a50</SimpleSelect.Option>
            <SimpleSelect.Option id="a51" value="a51">a51</SimpleSelect.Option>
            <SimpleSelect.Option id="a52" value="a52">a52</SimpleSelect.Option>
            <SimpleSelect.Option id="a53" value="a53">a53</SimpleSelect.Option>
            <SimpleSelect.Option id="a54" value="a54">a54</SimpleSelect.Option>
            <SimpleSelect.Option id="a55" value="a55">a55</SimpleSelect.Option>
            <SimpleSelect.Option id="a56" value="a56">a56</SimpleSelect.Option>
            <SimpleSelect.Option id="a57" value="a57">a57</SimpleSelect.Option>
            <SimpleSelect.Option id="a58" value="a58">a58</SimpleSelect.Option>
            <SimpleSelect.Option id="a59" value="a59">a59</SimpleSelect.Option>
            <SimpleSelect.Option id="a60" value="a60">a60</SimpleSelect.Option>
            <SimpleSelect.Option id="a61" value="a61">a61</SimpleSelect.Option>
            <SimpleSelect.Option id="a62" value="a62">a62</SimpleSelect.Option>
            <SimpleSelect.Option id="a63" value="a63">a63</SimpleSelect.Option>
            <SimpleSelect.Option id="a64" value="a64">a64</SimpleSelect.Option>
            <SimpleSelect.Option id="a65" value="a65">a65</SimpleSelect.Option>
            <SimpleSelect.Option id="a66" value="a66">a66</SimpleSelect.Option>
            <SimpleSelect.Option id="a67" value="a67">a67</SimpleSelect.Option>
            <SimpleSelect.Option id="a68" value="a68">a68</SimpleSelect.Option>
            <SimpleSelect.Option id="a69" value="a69">a69</SimpleSelect.Option>
            <SimpleSelect.Option id="a70" value="a70">a70</SimpleSelect.Option>
            <SimpleSelect.Option id="a71" value="a71">a71</SimpleSelect.Option>
            <SimpleSelect.Option id="a72" value="a72">a72</SimpleSelect.Option>
            <SimpleSelect.Option id="a73" value="a73">a73</SimpleSelect.Option>
            <SimpleSelect.Option id="a74" value="a74">a74</SimpleSelect.Option>
            <SimpleSelect.Option id="a75" value="a75">a75</SimpleSelect.Option>
            <SimpleSelect.Option id="a76" value="a76">a76</SimpleSelect.Option>
            <SimpleSelect.Option id="a77" value="a77">a77</SimpleSelect.Option>
            <SimpleSelect.Option id="a78" value="a78">a78</SimpleSelect.Option>
            <SimpleSelect.Option id="a79" value="a79">a79</SimpleSelect.Option>
            <SimpleSelect.Option id="a80" value="a80">a80</SimpleSelect.Option>
            <SimpleSelect.Option id="a81" value="a81">a81</SimpleSelect.Option>
            <SimpleSelect.Option id="a82" value="a82">a82</SimpleSelect.Option>
            <SimpleSelect.Option id="a83" value="a83">a83</SimpleSelect.Option>
            <SimpleSelect.Option id="a84" value="a84">a84</SimpleSelect.Option>
            <SimpleSelect.Option id="a85" value="a85">a85</SimpleSelect.Option>
            <SimpleSelect.Option id="a86" value="a86">a86</SimpleSelect.Option>
            <SimpleSelect.Option id="a87" value="a87">a87</SimpleSelect.Option>
            <SimpleSelect.Option id="a88" value="a88">a88</SimpleSelect.Option>
            <SimpleSelect.Option id="a89" value="a89">a89</SimpleSelect.Option>
            <SimpleSelect.Option id="a90" value="a90">a90</SimpleSelect.Option>
            <SimpleSelect.Option id="a91" value="a91">a91</SimpleSelect.Option>
            <SimpleSelect.Option id="a92" value="a92">a92</SimpleSelect.Option>
            <SimpleSelect.Option id="a93" value="a93">a93</SimpleSelect.Option>
            <SimpleSelect.Option id="a94" value="a94">a94</SimpleSelect.Option>
            <SimpleSelect.Option id="a95" value="a95">a95</SimpleSelect.Option>
            <SimpleSelect.Option id="a96" value="a96">a96</SimpleSelect.Option>
            <SimpleSelect.Option id="a97" value="a97">a97</SimpleSelect.Option>
            <SimpleSelect.Option id="a98" value="a98">a98</SimpleSelect.Option>
            <SimpleSelect.Option id="a99" value="a99">a99</SimpleSelect.Option>
        </SimpleSelect>
    )
}

export default SIMPLESELECT_X100_IUI