import React from 'react'
import { View } from '@instructure/ui'

const VIEW_X100_IUI = () => {
  return (
    <React.Fragment>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
      <View>asd</View>
    </React.Fragment>
  )
}

export default VIEW_X100_IUI